name: PVPlugin
version: ${project.version}
main: me.kitdacatsun.pvplugin.PVPlugin
api-version: 1.16

commands:
  join:
    description: Adds player to team
    usage: "Usage: /<command> [red|blue|none]"
    aliases: ["join Red", "join Blue", "join None"]
  startgame:
    description: Starts the game
    aliases: ["sg"]
  endgame:
    description: Ends the game
    aliases: ["eg"]
  spawn:
    description: Sends player to spawn
  readt:
    description: Sets player as ready
    aliases: ["r"]