name: PVPlugin
version: ${project.version}
main: me.kitdacatsun.pvplugin.PVPlugin
api-version: 1.16

commands:
  join:
    description: Adds player to team
    usage: "Usage: /<command> [red|blue|none]"
    aliases: ["join Red", "join Blue", "join None"]
  start:
    description: Starts the game
    usage: "Usage: /<command>"