name: PVPlugin
version: 1.0-SNAPSHOT
main: me.kitdacatsun.pvplugin.PVPlugin
api-version: 1.16

commands:
  join:
    description: Adds player to team
    usage: "Usage: /<command> <red/blue>"
  ready:
    description: Ready's player
    usage: "Usage: /<command>"
